django-josephscrumy/josephscrumy/urls.py
from django.urls import path,include
from . import views

app_name = 'josephscrumy' 

urlpatterns = [
    path('', views.index, name="about"),
    path('movegoal/<int:goal_id>/', views.move_goal),
    path('addgoal/', views.add_goal),
    path('home/', views.home),
    path('accounts/',include('django.contrib.auth.urls')),
]

josephscrumy/urls.py
from django.urls import path,include
from . import views

app_name = 'josephscrumy' 

urlpatterns = [
    path('', views.index, name="about"),
    path('movegoal/<int:goal_id>/', views.move_goal, name="movegoal"),
    path('addgoal/', views.add_goal, name="add_goal"),
    path('home/', views.home, name="home"),
    path('accounts/',include('django.contrib.auth.urls')),
    path('success', views.sucessview, name="sucess"),
    path('logout/', views.logout_view, name="logout"),
    path('group/', views.groupview, name="group")
    
]

myscrumy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('favicon\.ico$',RedirectView.as_view(url='/static/images/favicon.ico')),
    path('josephscrumy/',include('josephscrumy.urls', namespace="josephscrumy")),
]

django-josephscrumy/josephscrumy/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class GoalStatus(models.Model):
    status_name = models.CharField(max_length=200)

    def __str__(self):
        return self.status_name


class ScrumyGoals(models.Model):
    user = models.ForeignKey(User, related_name='user', on_delete=models.CASCADE)
    goal_name = models.CharField(max_length=200)
    goal_id = models.IntegerField(unique=True)
    created_by = models.CharField(max_length=200)
    moved_by = models.CharField(max_length=200)
    owner = models.CharField(max_length=200)
    goal_status= models.ForeignKey(GoalStatus, on_delete=models.PROTECT)

    def __str__(self):
        return self.goal_name

    def __int__(self):
        return self.goal_id


class ScrumyHistory(models.Model):
    moved_by = models.CharField(max_length=200)
    created_by = models.CharField(max_length=200)
    moved_from = models.CharField(max_length=200)
    moved_to = models.CharField(max_length=200)
    time_of_action = models.DateTimeField(auto_now_add=True)
    goal = models.ForeignKey(ScrumyGoals, on_delete=models.PROTECT)

    def __str__(self):
        return self.created_by

josephscrumy/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class GoalStatus(models.Model):
    status_name = models.CharField(max_length=200)

    def __str__(self):
        return self.status_name


class ScrumyGoals(models.Model):
    user = models.ForeignKey(User, related_name='user', on_delete=models.CASCADE)
    goal_name = models.CharField(max_length=200)
    goal_id = models.IntegerField(unique=True)
    created_by = models.CharField(max_length=200)
    moved_by = models.CharField(max_length=200)
    owner = models.CharField(max_length=200)
    goal_status= models.ForeignKey(GoalStatus, on_delete=models.PROTECT)

    def __str__(self):
        return self.goal_name

    def __int__(self):
        return self.goal_id


class ScrumyHistory(models.Model):
    moved_by = models.CharField(max_length=200)
    created_by = models.CharField(max_length=200)
    moved_from = models.CharField(max_length=200)
    moved_to = models.CharField(max_length=200)
    time_of_action = models.DateTimeField(auto_now_add=True)
    goal = models.ForeignKey(ScrumyGoals, on_delete=models.PROTECT)

    def __str__(self):
        return self.created_by

josephscrumy/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group, User
from django.forms.forms import Form
from .models import ScrumyGoals,GoalStatus

User = get_user_model()
fields = ['first_name', 'last_name', 'email', 'username', 'password']

class SignupForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username']
        help_texts = {
            'username': None,
            'email': None,
        }
    
    def clean(self):
        cleaned_data = super(SignupForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError("password and confirm_password does not match")
        return cleaned_data

    def save(self, commit = True):
        user = super(SignupForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user
        


class CreateGoalForm(forms.ModelForm):
    class Meta:
        model = ScrumyGoals
        fields = ['goal_name',]


class MovrGoalForm(forms.ModelForm):
    class Meta:
        model = ScrumyGoals
        fields = ['goal_status',]



Form_group =( 
    ("--- Choose ---", "--- Choose ---"),
    ("Developer", "Developer"), 
    ("Owner", "Owner"), 
    ("Admin", "Admin"), 
    ("Quality Assurance", "Quality Assurance")
)



class SwitchGroupForm(forms.Form):
    name = forms.ChoiceField(choices = Form_group)

django-josephscrumy/josephscrumy/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.models import User

from .models import (GoalStatus, ScrumyGoals, ScrumyHistory)
import random
# Create your views here.

# def get_grading_parameters(request):
#     return HttpResponse('Welcome to Django')

def index(request):
    # return HttpResponse('This is a Scrum Application')
    goal = ScrumyGoals.objects.filter(goal_name='Learn Django')
    return HttpResponse(goal)


def move_goal(request, goal_id):
    # ScrumyGoals.objects.get(goal_id=goal_id)
    # goal = ScrumyGoals.objects.get(goal_name='Learn Django')
    # return HttpResponse(goal)
    try: 
        obj = ScrumyGoals.objects.get(goal_id=goal_id) 
    except Exception as e: 
        return render(
            request, 
            'josephscrumy/exception.html', 
            {'error': 'A record with that goal id does not exist'}
        )
    else: 
        return HttpResponse(obj.goal_name)


def add_goal(request):
    ScrumyGoals.objects.create(
        user=User.objects.get(username='LouisOma'),
        goal_name='Keep Learning Django',
        goal_id= random.randint(1000,9999),
        created_by = 'Louis',
        moved_by='Louis',
        owner='Louis',
        goal_status=GoalStatus.objects.get(status_name='Weekly Goal')
    )


# def home(request):
#     goal_name = ScrumyGoals.objects.get(goal_name='Learn Django')
#     goal_id = int(ScrumyGoals.objects.get(goal_id=1))
#     user = User.objects.get(username='louis')
#     context = {
#         'goal_name': goal_name,
#         'goal_id': goal_id,
#         'user': user,
#     }
#     return render(request, 'josephscrumy/home.html', context)

# def home(request):
#     to_display = ScrumyGoals.objects.filter(goal_name='Keep Learning Django')
#     output = ', '.join([eachgoal.goal_name for eachgoal in to_display])
#     return HttpResponse(output)


def home(request):
    user = User.objects.all()
    week = GoalStatus.objects.get(status_name="Weekly Goal")
    weeke = week.scrumygoals_set.all()
    daily = GoalStatus.objects.get(status_name="Daily Goal")
    dailyed =daily.scrumygoals_set.all()
    verify = GoalStatus.objects.get(status_name="Verify Goal")
    verifyed=verify.scrumygoals_set.all()
    done = GoalStatus.objects.get(status_name="Done Goal")
    doneed =done.scrumygoals_set.all()
    
    

    # context = {
    #     'user': user,
    #     'done':doneed,
    #     'verify':verifyed,
    #     'daily':dailyed,
    #     'week':weeke
    # }
    context = {
        'user': User.objects.all(),
        'done':GoalStatus.objects.get(status_name="Done Goal").scrumygoals_set.all(),
        'verify':GoalStatus.objects.get(status_name="Verify Goal").scrumygoals_set.all(),
        'daily':GoalStatus.objects.get(status_name="Daily Goal").scrumygoals_set.all(),
        'week':GoalStatus.objects.get(status_name="Weekly Goal").scrumygoals_set.all()
    }
    return render(request, 'josephscrumy/home.html', context)
    

josephscrumy/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from .forms import CreateGoalForm,SignupForm,MovrGoalForm,SwitchGroupForm

from .models import (GoalStatus, ScrumyGoals, ScrumyHistory)
import random
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout,login

# def get_grading_parameters(request):
#     return HttpResponse('Welcome to Django')

def index(request):
    # return HttpResponse('This is a Scrum Application')
    # goal = ScrumyGoals.objects.filter(goal_name='Learn Django')
    # return HttpResponse(goal)
        
    if request.method == 'POST':
        user_form = SignupForm(request.POST)
        if user_form.is_valid():
            user_form.save()
            my_group = Group.objects.get(name = 'Developer')
            get_user_id = User.objects.get(username = user_form.cleaned_data['username'])
            my_group.user_set.add(get_user_id)
            return redirect('/josephscrumy/accounts/login/')
            return HttpResponse("Your account has been created successfully")
        
        else:
            return redirect("josephscrumy:about")

    else:
        user_form = SignupForm()
        return render(request, 'josephscrumy/index.html', context={"user_form": user_form})

#lflllflf

def sucessview(request):
    return render(request, 'josephscrumy/success.html')



@login_required(login_url='/josephscrumy/accounts/login/')
def move_goal(request, goal_id):
    # ScrumyGoals.objects.get(goal_id=goal_id)
    # goal = ScrumyGoals.objects.get(goal_name='Learn Django')
    # return HttpResponse(goal)
    try: 
        obj = ScrumyGoals.objects.get(goal_id=goal_id) 
    except Exception as e: 
        return render(
            request, 
            'josephscrumy/exception.html', 
            {'error': 'A record with that goal id does not exist'}
        )
    else: 
        if request.method == 'POST':
            form = MovrGoalForm(request.POST)
            if form.is_valid():
                forms = form.cleaned_data['goal_status']
               
                Owner = Group.objects.get(name ="Owner")
                Developer = Group.objects.get(name ="Developer")
                qty = Group.objects.get(name ="Quality Assurance")
                ad = Group.objects.get(name ="Admin")
                donegoal = GoalStatus.objects.get(status_name = "Done Goal")
                weeklygoal = GoalStatus.objects.get(status_name = "Weekly Goal")

                if obj.goal_status == forms:
                    return HttpResponse("you cannot move your current goal back to yourself")
                else:
                    if obj.user == request.user:
                        
                        if Developer in request.user.groups.all():
                            if forms == donegoal:
                                return HttpResponse("A member of the 'Developer' group cannot move goals to done goal status")
                            else:
                                obj.goal_status = forms
                                obj.save()
                                return redirect("josephscrumy:home")
                        elif qty in request.user.groups.all():
                            if forms == weeklygoal:
                                return HttpResponse("A member of the 'Quality Assurance' group cannot move goals to weekly goal status")
                            else:
                                obj.goal_status = forms
                                obj.save()
                                return redirect("josephscrumy:home")
                        elif Owner in request.user.groups.all():
                            obj.goal_status = forms
                            obj.save()
                            return redirect("josephscrumy:home")

                    elif qty in request.user.groups.all():
                        if forms == donegoal:
                            obj.goal_status = forms
                            obj.save()
                            return redirect("josephscrumy:home")
                        else:
                            return HttpResponse("The permission is only granted for 'Done Goal'....!")

                    elif ad in request.user.groups.all():
                        obj.goal_status = forms
                        obj.save()
                        return redirect("josephscrumy:home")

                    else:
                        return HttpResponse("You don't have the right to move anybody's goal")
            else:
                return redirect("josephscrumy:add_goal")
        else:
            form = MovrGoalForm()
            return render(request, 'josephscrumy/move.html', context={"form": form})



@login_required(login_url='/josephscrumy/accounts/login/')
def add_goal(request):
    if request.method == 'POST':
        add_main_goal = CreateGoalForm(request.POST)
        if add_main_goal.is_valid():
            if request.user:
                ScrumyGoals.objects.create(
                    user= request.user,
                    goal_name=add_main_goal.cleaned_data['goal_name'],
                    goal_id= random.randint(1000,9999),
                    created_by = 'Louis',
                    moved_by='Louis',
                    owner='Louis',
                    goal_status=GoalStatus.objects.get(status_name='Weekly Goal')
                )
                return redirect("josephscrumy:home")
            else:
                return HttpResponse("A user with the group of 'Developer' can only create goal for himself")
        else:
            return redirect("josephscrumy:add_goal")

    else:
        goal_form = CreateGoalForm()
        return render(request, 'josephscrumy/create.html', context={"user_form": goal_form, "grouped": Group.objects.get(name = "Developer")})


# def home(request):
#     goal_name = ScrumyGoals.objects.get(goal_name='Learn Django')
#     goal_id = int(ScrumyGoals.objects.get(goal_id=1))
#     user = User.objects.get(username='louis')
#     context = {
#         'goal_name': goal_name,
#         'goal_id': goal_id,
#         'user': user,
#     }
#     return render(request, 'josephscrumy/home.html', context)

# def home(request):
#     to_display = ScrumyGoals.objects.filter(goal_name='Keep Learning Django')
#     output = ', '.join([eachgoal.goal_name for eachgoal in to_display])
#     return HttpResponse(output)


def home(request):
    user = User.objects.all()
    week = GoalStatus.objects.get(status_name="Weekly Goal")
    weeke = week.scrumygoals_set.all()
    daily = GoalStatus.objects.get(status_name="Daily Goal")
    dailyed =daily.scrumygoals_set.all()
    verify = GoalStatus.objects.get(status_name="Verify Goal")
    verifyed=verify.scrumygoals_set.all()
    done = GoalStatus.objects.get(status_name="Done Goal")
    doneed =done.scrumygoals_set.all()
    
    

    # context = {
    #     'user': user,
    #     'done':doneed,
    #     'verify':verifyed,
    #     'daily':dailyed,
    #     'week':weeke
    # }
    context = {
        'user': User.objects.all(),
        'done':GoalStatus.objects.get(status_name="Done Goal").scrumygoals_set.all(),
        'verify':GoalStatus.objects.get(status_name="Verify Goal").scrumygoals_set.all(),
        'daily':GoalStatus.objects.get(status_name="Daily Goal").scrumygoals_set.all(),
        'week':GoalStatus.objects.get(status_name="Weekly Goal").scrumygoals_set.all(),
        'dev':Group.objects.get(name = 'Developer')
    }
    return render(request, 'josephscrumy/home.html', context)
    


@login_required(login_url='/josephscrumy/accounts/login/')
def logout_view(request):
    logout(request)
    return redirect('/josephscrumy/accounts/login/')



def groupview(request):
    if request.method == 'POST':
        form = SwitchGroupForm(request.POST)
        if form.is_valid():
            try: 
                g = Group.objects.get(name = form.cleaned_data['name'])
            except Exception as e: 
                return HttpResponse("Sorry, no such group")
            else:
                user_group = User.groups.through.objects.get(user=request.user)
                user_group.group = g
                user_group.save()
                return redirect("josephscrumy:home")
        else:
            return redirect("josephscrumy:group")
    else:
        form = SwitchGroupForm()
        return render(request, 'josephscrumy/group.html', context = {"form": form})

josephscrumy/templates/josephscrumy/create.html
{% extends 'base.html' %}
{% block title %}
  Add goals
{% endblock title %}

{% block content %}
  <form method="post" action="{% url 'josephscrumy:add_goal' %}">
        {% csrf_token %}
        {{user_form.as_p}}
        <input type="submit" value="Submit">
    </form>
    <br /><br />
    {% if user.is_authenticated %}
      {% for group in user.groups.all %}
          {% if group == grouped %}
            <span>Your group is 'Developer' so, you won't be able to create goal for another user</span>
          {% endif %}
        {% endfor %}</p>
    {% endif %}
{% endblock content %}

josephscrumy/templates/josephscrumy/exception.html
<p>{{ error }}</p>

josephscrumy/templates/josephscrumy/group.html
{% extends 'base.html' %}
{% block title %}
  Change group
{% endblock title %}

{% block content %}
  <form method="post" action="{% url 'josephscrumy:group' %}">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit">
    </form>
    <br /><br />
    
{% endblock content %}

josephscrumy/templates/josephscrumy/home.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>{% block title%} {% endblock title %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="#">Scrumy app</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="visibility: hidden;">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        {% if request.user.is_authenticated %}
            <p style="position: relative; right: 40px;">User: {{request.user.username}}<br /> Group: {% for group in request.user.groups.all %}
                {{ group }}{% endfor %}</p>
            <a href="{% url 'josephscrumy:group' %}" class="btn btn-outline-success" type="submit">Change group</a>
            <a href="{% url 'josephscrumy:logout' %}" class="btn btn-outline-success" type="submit">Logout</a>
        {% else %}
            <a href="{% url 'josephscrumy:login' %}" class="btn btn-outline-success" type="submit">Login</a>
            <a href="{% url 'josephscrumy:about' %}" class="btn btn-outline-success" type="submit">Register</a>
        {% endif %}
        
      </form>
    </div>
  </div>
</nav>

    <div class="container">
    <h1>Scrumy User table</h1>


    <table class="table">
  <thead>
    <tr>
      <th>User</th>
        <th>Weekly Goals</th>
        <th>Daily Goals</th>
        <th>Verify Goals</th>
        <th>Done Goals</th>
    </tr>
  </thead>
  <tbody>
  {% for x in user %}
    <tr>
    <td>
      {{x.username}}
    </td>
    <td>
    {% for goals in week %}
      {% if goals.user == x %}
        {{ goals.goal_id }}. {{ goals }} <br />
        {% for group in request.user.groups.all %}
                {% if group == dev %}
                  {% if goals.user == request.user %}
                    <a href="{% url 'josephscrumy:movegoal' goals.goal_id %}">Move goal</a><br /><br />
              
                  {% endif %}
                {% else %}
                  <a href="{% url 'josephscrumy:movegoal' goals.goal_id %}">Move goal</a><br /><br />
                {% endif %}
        {% endfor %}
        
      {% endif %}
    {% endfor %}
    </td>

    <td>
    {% for goals in daily %}
      {% if goals.user == x %}
        {{ goals.goal_id }}. {{ goals.goal_name }} <br />
        {% for group in request.user.groups.all %}
                {% if group == dev %}
                  {% if goals.user == request.user %}
                    <a href="{% url 'josephscrumy:movegoal' goals.goal_id %}">Move goal</a><br /><br />
              
                  {% endif %}
                {% else %}
                  <a href="{% url 'josephscrumy:movegoal' goals.goal_id %}">Move goal</a><br /><br />
                {% endif %}
        {% endfor %}
      {% endif %}
    {% endfor %}
    </td>

    <td>
    {% for goals in verify %}
      {% if goals.user == x %}
        {{ goals.goal_id }}. {{ goals.goal_name }} <br />
        {% for group in request.user.groups.all %}
                {% if group == dev %}
                  {% if goals.user == request.user %}
                    <a href="{% url 'josephscrumy:movegoal' goals.goal_id %}">Move goal</a><br /><br />
              
                  {% endif %}
                {% else %}
                  <a href="{% url 'josephscrumy:movegoal' goals.goal_id %}">Move goal</a><br /><br />
                {% endif %}
        {% endfor %}
      {% endif %}
    {% endfor %}
    </td>

    <td>
    {% for goals in done %}
      {% if goals.user == x %}
        {{ goals.goal_id }}. {{ goals.goal_name }} <br />
        {% for group in request.user.groups.all %}
                {% if group == dev %}
                  {% if goals.user == request.user %}
                    <a href="{% url 'josephscrumy:movegoal' goals.goal_id %}">Move goal</a><br /><br />
              
                  {% endif %}
                {% else %}
                  <a href="{% url 'josephscrumy:movegoal' goals.goal_id %}">Move goal</a><br /><br />
                {% endif %}
        {% endfor %}
      {% endif %}
    {% endfor %}
    </td>
      
    </tr>
    {% endfor %}
    </body>
    </table>

    <a href="{% url 'josephscrumy:add_goal' %}">Add goal</a>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    -->
  </body>
</html>

josephscrumy/templates/josephscrumy/index.html
{% extends 'base.html' %}

{% block title %}
  Index
{% endblock title %}

{% block content %}
  <div class="container">
      <h1>Signup form</h1>


      <form method="POST" action="{% url 'josephscrumy:about' %}">
          {% csrf_token %}
          {{user_form.as_p}}
          <input type="submit" value="Submit">
      </form>
    </div>
{% endblock content %}

josephscrumy/templates/josephscrumy/move.html
{% extends 'base.html' %}
{% block title %}
  move goal
{% endblock title %}

{% block content %}
    <div class="container">
        <h1>Move goal form</h1>


        <form method="POST" action="">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Submit">
        </form>

        {% comment %} <a href="{% url 'josephscrumy:add_goal' %}">Add goal</a> {% endcomment %}
    </div>
{% endblock content %}

josephscrumy/templates/josephscrumy/success.html
Your account has been created successfully